### PR TITLE
created methods for Grid

### PR DESCRIPTION
**Pull request by jkomendant**

### CODE REVIEW

**Comment by rpeikes** [comment]
Looks good to me so far

**Review by shweinfeld — COMMENTED** [review]
Why Boolean and not boolean?
Also, I need a way to set elements in the grid....I think

**Comment by jkomendant** [comment]
> Why Boolean and not boolean?
> Also, I need a way to set elements in the grid....I think

Good point. Adjusted it accordingly

**Review by shweinfeld — APPROVED** [review]
Nice!

**Comment by rpeikes** [comment]
@jkomendant could you add back the method to access the entire array? I'm not sure whether I'll end up utilizing it but for now It would be good to be able to play around with just for visual sake

**Pull request merged**
